apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-standard
  namespace: standard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi